# Generated by Django 4.1.5 on 2023-01-25 16:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbateDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.DateField(unique=True)),
                (
                    "cortes_suinos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                            validators=[django.core.validators.MinValueValidator(0.0)]
                        ),
                        size=None,
                    ),
                ),
                (
                    "cortes_carneiros",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                            validators=[django.core.validators.MinValueValidator(0.0)]
                        ),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Romaneio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="romaneios",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cortes_suinos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                            validators=[django.core.validators.MinValueValidator(0.0)]
                        ),
                        size=None,
                    ),
                ),
                (
                    "cortes_carneiros",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                            validators=[django.core.validators.MinValueValidator(0.0)]
                        ),
                        size=None,
                    ),
                ),
                (
                    "abate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="registros.abatediario",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "romaneio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="registros.romaneio",
                    ),
                ),
            ],
        ),
    ]
