# Generated by Django 4.1.5 on 2023-01-25 16:10

import django.core.validators
from django.db import migrations, models
import veiculos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "placa",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.MinLengthValidator(7),
                            django.core.validators.RegexValidator(
                                message="Placa inválida.",
                                regex="[A-Z]{3}[0-9][0-9A-Z][0-9]{2}",
                            ),
                        ],
                        verbose_name="Placa",
                    ),
                ),
                (
                    "renavam",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            veiculos.models.validate_renavam,
                        ],
                        verbose_name="Revanam",
                    ),
                ),
            ],
        ),
    ]
